import NavBar from "@/components/menubar/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <NavBar />
      <div className="flex flex-row">
        <div className="min-h-screen w-full justify-center bg-#F2F8FD">
          {children}
        </div>
      </div>
    </>
  );
}
